const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
let envContent = '';
if (fs.existsSync(envPath)) {
  envContent = fs.readFileSync(envPath, 'utf8');
}

// Read a key from .env, falling back to process.env then the provided default.
const readEnv = (key, fallback) => {
  const match = envContent.match(new RegExp(`^\\s*${key}\\s*=\\s*([^\\r\\n]+)`, 'm'));
  if (match && match[1]) {
    // Strip surrounding quotes if present
    return match[1].trim().replace(/^['"]|['"]$/g, '');
  }
  return process.env[key] || fallback;
};

// Coerce a numeric knob to a positive integer, falling back on bad input.
const toPositiveInt = (raw, fallback) => {
  const n = Math.floor(Number(raw));
  return Number.isFinite(n) && n >= 1 ? n : fallback;
};

const backendUrl = readEnv('BACKEND_URL', 'http://127.0.0.1:8000');
// Cluster-summary tuning (see ClusterSummaryService): how many summary streams
// run concurrently per hierarchy level, and how many top-scoring papers per
// cluster are sent to the summarization prompt.
const summaryConcurrency = toPositiveInt(readEnv('SUMMARY_CONCURRENCY', '8'), 8);
const summaryTopK = toPositiveInt(readEnv('SUMMARY_TOP_K', '15'), 15);
// How many sibling-cluster fingerprints (co-parented, highest-size first) are
// bundled into each summarization prompt for contrastive context.
const summarySiblingCap = toPositiveInt(readEnv('SUMMARY_SIBLING_CAP', '12'), 12);
// On-demand (Cloud Run scale-to-zero) model warm-up notice. If the first summary
// token takes longer than this many seconds, the UI assumes a cold start and
// shows a "please be patient" notice. The minute value only shapes that copy.
const summaryColdStartNoticeSec = toPositiveInt(readEnv('SUMMARY_COLD_START_NOTICE_SEC', '6'), 6);
const summaryWarmupMinutes = toPositiveInt(readEnv('SUMMARY_WARMUP_MINUTES', '1'), 1);

// Ensure directory exists
const envDir = path.join(__dirname, 'src', 'environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const envFileContent = `// This file is auto-generated by generate-env.js
export const environment = {
  BACKEND_URL: '${backendUrl}',
  SUMMARY_CONCURRENCY: ${summaryConcurrency},
  SUMMARY_TOP_K: ${summaryTopK},
  SUMMARY_SIBLING_CAP: ${summarySiblingCap},
  SUMMARY_COLD_START_NOTICE_SEC: ${summaryColdStartNoticeSec},
  SUMMARY_WARMUP_MINUTES: ${summaryWarmupMinutes}
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), envFileContent);
console.log(
  `[generate-env] Generated environment.ts with BACKEND_URL: ${backendUrl}, ` +
  `SUMMARY_CONCURRENCY: ${summaryConcurrency}, SUMMARY_TOP_K: ${summaryTopK}, ` +
  `SUMMARY_SIBLING_CAP: ${summarySiblingCap}, ` +
  `SUMMARY_COLD_START_NOTICE_SEC: ${summaryColdStartNoticeSec}, ` +
  `SUMMARY_WARMUP_MINUTES: ${summaryWarmupMinutes}`,
);
