const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
let backendUrl = process.env.BACKEND_URL || 'http://127.0.0.1:8000';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const match = envContent.match(/^\s*BACKEND_URL\s*=\s*([^\r\n]+)/m);
  if (match && match[1]) {
    backendUrl = match[1].trim();
    // Strip surrounding quotes if present
    backendUrl = backendUrl.replace(/^['"]|['"]$/g, '');
  }
}

// Ensure directory exists
const envDir = path.join(__dirname, 'src', 'environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const envFileContent = `// This file is auto-generated by generate-env.js
export const environment = {
  BACKEND_URL: '${backendUrl}'
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), envFileContent);
console.log(`[generate-env] Generated environment.ts with BACKEND_URL: ${backendUrl}`);
